### ISSUE TITLE
Beta Feedback

### ISSUE THREAD

**Issue by catinthecradle** [sopra-fs22-group-26/client#173]
**Problems:**

Data validation
- [x] sopra-fs22-group-26/server#296

/signup
- [x] sopra-fs22-group-26/client#175

/dashboard
- [x] sopra-fs22-group-26/client#179
- [x] One can choose a date of birth on the profile page, that lies far in the future or in the middle ages
- [x] can complete task (with icon) without assigning points

/reports
- [x] Make open/closed reports more visible, took me a while to get that i have to click on upcoming.

/creationform
- [x] sopra-fs22-group-26/client#178
 
/profile
- [x] can create tasks with deadline in the past
- [x] sopra-fs22-group-26/server#295

**Questions/Suggestions:**
- [x] It is possible to create tasks, where no one is assigned and there is no reporter. Is this intended?
- [x] Why does it say no comment in the task? Is there going to be the possibility to make comments?
- [x] sopra-fs22-group-26/client#181
- [x] What is the difference between open and upcoming reports?
- [x] sopra-fs22-group-26/client#182
- [x] sopra-fs22-group-26/client#183
- [x] What are estimate poll sessions?
- [x] You can change the tasks even if you are not an assignee or reporter. Then mark the task as completed and give 5 points. Hence you win on the Scoreboard. Is this intended, too?
- [x] If there are a lot of people using it, it would be cool if one could favorite some people so that they are first in the list.
- [x] sopra-fs22-group-26/client#187
- [x] It is possible to make the “task description” field bigger, but you can not write much unless you want to provoke a server error. Is it possible to allow it to make a more detailed task description?

**Comment by catinthecradle** [comment]
We did everything!
